export default {
  queryCount: '报告查询次数',
  loanCount: '贷款笔数',
  loanTenantCount: '贷款机构数',
  averageLoanGapDays: '平均申请间隔时长',
  averageTenantGapDays: '平均换新机构间隔时长',
  maxLoanAmount: '最大贷款金额',
  maxLoanPeriodDays: '最大贷款天数',
  averageLoanAmount: '平均贷款额度',
  maxOverdueDays: '最大逾期天数',
  overdueLoanCount: '当前逾期的贷款笔数',
  overdueTenantCount: '当前逾期的贷款机构数',
  overdueFor2TermTenantCount: '逾期2周期以上的机构数(除小额拖欠)',
  daysFromLastLoan: '最后一次贷款距今天数',
  monthsFromFirstLoan: '最早贷款距今月数',
  monthsFromLastOverdue: '最后一次逾期距今月数',
  monthsForNormalRepay: '连续正常还款月数',
  remainingAmount: '未还款总余额',
  openLoanCount: '未结清贷款笔数',
  remainingOverdueAmount: '当前逾期金额',
  overdueCount: '累计逾期次数',
}